### ISSUE TITLE
Feature: Explicitly show users that they must log in with stuy.edu accounts

### ISSUE THREAD

**Issue by TheEgghead27** [stuysu/opportunities.stuysu.org#91]
This has been a recurring source of confusion for parents.

**Comment by SnowyNate** [comment]
Explicitly showing users that they must log in with stuy.edu acct through a little highlighted text box, or something that checks if the email entered is a stuy.edu email? Just curious.

**Comment by TheEgghead27** [comment]
The API already rejects non Stuy emails, but it would be good to have red error text show up

**Comment by SnowyNate** [comment]
> The API already rejects non Stuy emails, but it would be good to have red error text show up

Got it, should be a relatively simple issue to fix then- I would if I had time... and my laptop back from repair
